[package]
name = "test_smart_pointer"
version = "0.1.0"
authors = ["hao.liu <hao.liu@aimapnet.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
